### ISSUE TITLE
Why is there no "centered" container?

### ISSUE THREAD

**Issue by masbaehr** [teodosii/react-notifications-component#46]
It would be very useful to have an extra container to show a message at the center of the screen. 
It could be implemented very easily by doing the following:

 `<div class="notification-container-center-center">`

```css
.notification-container-center-center {
    transform: translateX(-50%);
    top: 50%;
    left: 50%;
}
```
