### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by adhip94** [teodosii/react-notifications-component#84]
Can we use a custom font for the text in the popup?

![](https://user-images.githubusercontent.com/20703483/94788019-a62e0400-03f0-11eb-9e21-0acbfa739e6a.png) 

This doesnt look great...

**Comment by teodosii** [comment]
This is up to you to change the stylesheet to include any font you want.
Maybe in the future version I will include a font file in the style as well, but for now you need to stick to whatever font you want.\

```css
html,
body,
.notification-parent,
.notification-title,
.notification-message,
.notification-item {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial,
  sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol' !important;
}
```

This is what's being used on samples project
