### ISSUE TITLE
Customize theme with custom color

### ISSUE THREAD

**Issue by barakjobs** [teodosii/react-notifications-component#87]
How can I add a custom color, like for success I want blue. 
Can you please help me on this.

**Comment by ImCorfitz** [comment]
You can easily do this by changing the values in the CSS files to be included. I manually import the SASS files in my NEXT.js project, and there you'll find a `_variables.scss` file, which allows you to change the hex values for either one. 

![Screenshot 2020-11-21 at 11 00 30](https://user-images.githubusercontent.com/52371939/99875595-c6a45e80-2be8-11eb-84c4-e4bbb217d34a.png)

**Comment by ImCorfitz** [comment]
Should you prefer, you can also change the compiled CSS stylesheet manuelly and include this isntead of the one included in the package:

```css

.notification-container--bottom-center,
.notification-container--bottom-full,
.notification-container--bottom-left,
.notification-container--bottom-right,
.notification-container--center,
.notification-container--top-center,
.notification-container--top-full,
.notification-container--top-left,
.notification-container--top-right {
  min-width: 325px;
  position: absolute;
  pointer-events: all;
}
.notification-container--bottom-center,
.notification-container--center,
.notification-container--top-center {
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  left: calc(50% - 175px);
  max-width: 350px;
}
.notification-container--center {
  top: 20px;
  height: 100%;
  pointer-events: none;
}
.notification-container--bottom-full,
.notification-container--top-full {
  width: 100%;
  min-width: 100%;
}
.notification-container--bottom-full {
  bottom: 0;
}
.flex-center {
  min-width: 325px;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  pointer-events: all;
}
.notification-container--top-center {
  top: 20px;
}
.notification-container--bottom-center {
  bottom: 20px;
}
.notification-container--top-left {
  left: 20px;
  top: 20px;
}
.notification-container--top-right {
  right: 20px;
  top: 20px;
}
.notification-container--bottom-left {
  left: 20px;
  bottom: 20px;
}
.notification-container--bottom-right {
  bottom: 20px;
  right: 20px;
}
.notification-container--mobile-bottom,
.notification-container--mobile-top {
  pointer-events: all;
  position: absolute;
}
.notification-container--mobile-top {
  right: 20px;
  left: 20px;
  top: 20px;
}
.notification-container--mobile-bottom {
  right: 20px;
  left: 20px;
  bottom: 20px;
  margin-bottom: -15px;
}
.notification__item--default {
  background-color: #007bff;
  border-left: 8px solid #0562c7;
}
.notification__item--default .notification__timer {
  background-color: #007bff;
}
.notification__item--default .notification__timer-filler {
  background-color: #fff;
}
.notification__item--default .notification__close {
  background-color: #007bff;
}
.notification__item--success {
  background-color: #28a745;
  border-left: 8px solid #1f8838;
}
.notification__item--success .notification__timer {
  background-color: #28a745;
}
.notification__item--success .notification__timer-filler {
  background-color: #fff;
}
.notification__item--success .notification__close {
  background-color: #28a745;
}
.notification__item--danger {
  background-color: #dc3545;
  border-left: 8px solid #bd1120;
}
.notification__item--danger .notification__timer {
  background-color: #dc3545;
}
.notification__item--danger .notification__timer-filler {
  background-color: #fff;
}
.notification__item--danger .notification__close {
  background-color: #dc3545;
}
.notification__item--info {
  background-color: #17a2b8;
  border-left: 8px solid #138b9e;
}
.notification__item--info .notification__timer {
  background-color: #17a2b8;
}
.notification__item--info .notification__timer-filler {
  background-color: #fff;
}
.notification__item--info .notification__close {
  background-color: #17a2b8;
}
.notification__item--warning {
  background-color: #eab000;
  border-left: 8px solid #ce9c09;
}
.notification__item--warning .notification__timer {
  background-color: #eab000;
}
.notification__item--warning .notification__timer-filler {
  background-color: #fff;
}
.notification__item--warning .notification__close {
  background-color: #eab000;
}
.notification__item--awesome {
  background-color: #685dc3;
  border-left: 8px solid #4c3fb1;
}
.notification__item--awesome .notification__timer {
  background-color: #685dc3;
}
.notification__item--awesome .notification__timer-filler {
  background-color: #fff;
}
.notification__item--awesome .notification__close {
  background-color: #685dc3;
}
@keyframes timer {
  0% {
    width: 100%;
  }
  to {
    width: 0;
  }
}
.notifications-component {
  position: fixed;
  z-index: 9000;
  pointer-events: none;
  width: 100%;
  height: 100%;
}
.notification__item {
  display: flex;
  position: relative;
  border-radius: 3px;
  margin-bottom: 15px;
  box-shadow: 1px 3px 4px rgba(0, 0, 0, 0.2);
  cursor: pointer;
}
.notification-container--bottom-full .notification__item,
.notification-container--top-full .notification__item {
  margin-bottom: 0;
  border-radius: 0;
}
.notification__timer {
  width: 100%;
  margin-top: 10px;
}
.notification__timer,
.notification__timer-filler {
  height: 3px;
  border-radius: 5px;
}
.notification__title {
  color: #fff;
  font-weight: 700;
  font-size: 14px;
  margin-top: 5px;
  margin-bottom: 5px;
}
.notification__message {
  color: #fff;
  max-width: calc(100% - 15px);
  font-size: 14px;
  line-height: 150%;
  word-wrap: break-word;
  margin-bottom: 0;
  margin-top: 0;
}
.notification__content {
  padding: 8px 15px;
  display: inline-block;
  width: 100%;
}
.notification__close {
  width: 18px;
  height: 18px;
  border-radius: 50%;
  display: inline-block;
  position: absolute;
  right: 10px;
  top: 10px;
}
.notification__close:after {
  content: "\D7";
  position: absolute;
  transform: translate(-50%, -50%);
  color: #fff;
  font-size: 12px;
  left: 50%;
  top: 50%;
}
.notification-container--mobile-bottom .notification,
.notification-container--mobile-bottom .notification__item,
.notification-container--mobile-top .notification,
.notification-container--mobile-top .notification__item {
  max-width: 100%;
  width: 100%;
}
.notification-container--bottom-right .notification,
.notification-container--top-right .notification {
  margin-left: auto;
}
.notification-container--bottom-left .notification,
.notification-container--top-left .notification {
  margin-right: auto;
}
.notification-container--mobile-bottom .notification,
.notification-container--mobile-top .notification {
  margin-left: auto;
  margin-right: auto;
}

```
